### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by Ruin0x11** [Ruin0x11/intellij-lsp-server#12]
A bunch of things are breaking on Linux for some reason.

- Document versions are always being mismatched.
- Completions don't resolve, likely because of the version mismatches.
- Various others.

**Comment by kleewho** [comment]
Hi, I'd like to tackle this version mismatches. Is there anything that might be helpful when working on it?

**Comment by Ruin0x11** [comment]
Yes, the primary version tracking logic is in the `WorkspaceManager` class right now. Whenever notifications like `textDocument/didChange` come in the state of the document is updated inside a separate map of 'URI -> text document' in the manager. You can turn on debugging for the `WorkspaceManager` by going to `Help -> Debug Log Settings...` in the debug IDEA instance and inserting `#com.ruin.lsp.model.WorkspaceManager` on a separate line. Then the details of each call will be output.

Thanks for contributing.

**Comment by kleewho** [comment]
I'm pretty sure I'm doing it wrong. I don't get almost any details at output. Should I add this when running `runIde` or when plugin is *officially* installed? I guess there shouldn't be any difference there. Should the line have preceding `#`? I've tried both version and neither work.

**Comment by Ruin0x11** [comment]
It is a bit confusing. The debug output is produced in the `idea.log` file. You can follow it by running this in the root:

```
tail -f build/idea-sandbox/system/log/idea.log
```

Also if you have the `Run` configuration setup in your *parent* copy of idea (the one you develop the plugin with), it will have the `idea.log` output placed in a separate output tab when you run it. Problem is the `.idea` folder containing the config is overwritten when importing the project, so you'll have to grab the `.idea/runConfigurations` folder in master containing `Run.xml` and place it in your copy of `.idea` for it to appear.

There should also be a preceding `#` in the debug list. [Here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241115-How-to-Collecting-PhpStorm-WebStorm-debug-Logs) is an example. As a rule of thumb, to turn on debugging for a class write a '#' followed by the class' fully qualified name.

**Comment by kleewho** [comment]
Ok. I was expecting standard output. Now I can finally see the logs. From what I understand for now the first content change goes sideways and then you have version mismatch so most probably finding the issue with the first content change should help. Although I'm wondering is there any way to synchronize versions between server and client?

**Comment by Ruin0x11** [comment]
The idea is that the server should not modify the document because the truth is held by the client. (However the server can send a [workspace/applyEdit](https://microsoft.github.io/language-server-protocol/specification#workspace_applyEdit) command to make the client update its own copy) Since requests are handled more or less in sequence, and the client should always send a document open notification first thing, there shouldn't be issues with the server updating its ground truth or being unable to find symbols by the time text-aware commands come in afterwards.

**Comment by kleewho** [comment]
Sure. I guess I will have to get familiar with LSP specification sooner or later
