### ISSUE TITLE
Prevent opening of Memory Disk Conflict window

### ISSUE THREAD

**Issue by Ruin0x11** [Ruin0x11/intellij-lsp-server#39]
Because of the way the server handles modifying IntelliJ's instances of opened documents, the server should always treat in-memory changes as the ground truth and never try to look at the client's file. But IntelliJ has a feature where if a document has changed in-memory but not on disk, a popup appears asking the user which document is definitive. This should be prevented and the in-memory document loaded in all cases, since if `Load FS Changes` is selected the document instances will become out of sync. Also, the window blocks the server until it is closed. This can become frustrating as it can appear under the client window and doesn't seem to show up in the taskbar on Windows.

`FileDocumentManagerImpl` has the package-public method `setAskReloadFromDisk` for setting the conflict manager. However, the class in question, `MemoryDiskConflictWindow`, is package-public only, so attempting to override its functionality may be infeasible.

**Comment by DiegoVicen** [comment]
Just running into this problem. Is there a known workaround, i.e tell IntelliJ to select by default one of the options?

**Comment by Ruin0x11** [comment]
It doesn't seem like it, as far as I can tell. The class which opens the dialog is `MemoryDiskConflictResolver`. When a filesystem event is detected by the `FileDocumentManagerImpl` class, its `MemoryDiskConflictResolver` runs `beforeContentChange`, where it checks for conflicts. If there are any, `askReloadFromDisk` is called, which shows the dialog. There is no way to configure this in the current IntelliJ version. (the source is [here](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/openapi/fileEditor/impl/MemoryDiskConflictResolver.java#L89)).

It would be theoretically possible to subclass `MemoryDiskConflictResolver` to just ignore any conflicts and use reflection to call the method `setAskReloadFromDisk` of `FileDocumentManagerImpl` to set it (it is test-only). The issue is the class is package-private, so we can't just write a new class file with the overrides needed. So, the setting of the resolver would have to take place at runtime, which I'm not sure is possible because it can't be subclassed, unless there's some advanced reflection functionality I'm missing. Also, `FileDocumentManagerImpl` requires `MemoryDiskConflictResolver` to be `@NotNull`, so it would break if it were just set to `null`.

**Comment by martskins** [comment]
If I understood the help document on https://www.jetbrains.com/help/idea/file-cache-conflict.html we want intellij to actually load the FS file, as opposed to what is stated (unless I didn't understand correctly) in the first comment of this issue.

If that is the case, shouldn't using `FileDocumentManager.reloadFromDisk` (in `WorkspaceManager.onTextDocumentSaved`) instead of `FileDocumentManager.saveDocumentAsIs` be enough to fix this? I tried it by building a new version of the plugin with the mentioned change and it does seem to suppress the constant messages, but I'm not sure if/how that affects anything else, although the tests seem to pass.

It would probably be better if you tried it so I'd be happy to open a PR if that is needed.

**Comment by Ruin0x11** [comment]
Sure, please do. I remember trying something similar but it didn't work for some reason. I suspect it was a race condition or something, because the displaying of the popup depends on the timestamp of the on-disk file, so it would appear based on which editor gets the filesystem notification first. But if this works then it would be great.

**Comment by DiegoVicen** [comment]
I just checked #73 and in a small test project I have to learn Kotlin it does indeed seem to solve the problem. Thank you, @martskins!

**Comment by Ruin0x11** [comment]
Tested it out for a while and it seems to work well. Thank you for contributing.
