### ISSUE TITLE
Error when opening a Java file: Not a directory

### ISSUE THREAD

**Issue by skybert** [Ruin0x11/intellij-lsp-server#5]
Hi there,

this looks like an awesome extension to Emacs. I'd love for this to work as I'm using IDEA for debugging and refactoring already. 

However, my first attempts at getting this to work on a couple of my projects have been in vain. I'm getting this error when visiting a Java buffer:
```
File mode specification error: (file-error Opening directory Not a directory /home/torstein/src/my-project/my-core/src/main/java/net/skybert/Foo.java)
```

I do agree with the error message that the java file isn't a directory, but I don't see why it would think so. I've tried to start emacs with no configuration except the snippet below to rule out any problem in the rest of my Emacs configuration.

Is there something obvious I've missed out here?

-Torstein

```
(let ((default-directory "~/.emacs.d/elpa"))
  (normal-top-level-add-subdirs-to-load-path))

(require 'lsp-mode)
(require 'company-lsp)
(load "/usr/local/src/intellij-lsp-server/lsp-intellij.el")

(with-eval-after-load 'lsp-mode
  (require 'lsp-intellij)
  (add-hook 'java-mode-hook #'lsp-intellij-enable))
```

## Versions
- GNU Emacs 25.2.1
- .emacs.d/elpa/lsp-mode-20180304.935
- .emacs.d/elpa/company-lsp-20180216.2325
- .emacs.d/elpa/company-20180225.1741

**Comment by Ruin0x11** [comment]
I figured out the issue after some debugging. On linux it seems that `locate-dominating-file` can pass a file name to its predicate, so it should check if the path is a directory or not. I also realized that there are some decisions I made for the purpose of testing that are not cross-platform. I'll be able to fix these as soon as I merge in a major refactoring I was planning.

**Comment by Ruin0x11** [comment]
I made a PR at: https://github.com/Ruin0x11/intellij-lsp-server/pull/6. See if it fixes it for you.

**Comment by skybert** [comment]
Hi @Ruin0x11,

thanks for your prompt reply and fix. That does indeed fix the mentioned error, but on all my projects (except a simple one with one java file), I now get:

```
File mode specification error: (file-error make client process failed Connection refused :name lsp-intellij TCP connection :buffer nil :host 127.0.0.1 :service 8080 :nowait nil)
```

The error seems strange since there's indeed an IDEA process listening on port `8080` on localhost:

```
 # netstat -nlp | grep 8080
tcp6       0      0 127.0.0.1:8080          :::*                    LISTEN      16752/java
```

Process 16752 looks like the correct one.
```
$  ps ww -p 16752
  PID TTY      STAT   TIME COMMAND
16752 ?        Sl     1:54 /usr/lib/jvm/oracle-java8-jdk-amd64/bin/java -Didea.classpath.index.enabled=false -Didea.config.path=/usr/local/src/intellij-lsp-server/build/idea-sandbox/config -Didea.is.internal=true -Didea.platform.prefix=Idea -Didea.plugins.path=/usr/local/src/intellij-lsp-server/build/idea-sandbox/plugins -Didea.required.plugins.id=com.ruin.lsp -Didea.system.path=/usr/local/src/intellij-lsp-server/build/idea-sandbox/system -Dsun.awt.disablegrab=true -Xbootclasspath/a:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/boot.jar -XX:MaxPermSize=250m -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -ea -cp /usr/lib/jvm/oracle-java8-jdk-amd64/lib/tools.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/idea_rt.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/idea.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/bootstrap.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/extensions.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/util.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/openapi.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/trove4j.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/jdom.jar:/home/torstein/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.3.4/9f9a05f798720d7da2e3b3af8983552a840ed5d4/ideaIC-2017.3.4/lib/log4j.jar com.intellij.idea.Main
```

I've tried to restart the gradle process and emacs alike. Also tried to set up the project manually in IDEA (through `gradle runIdea`) to make sure there's no problem there, then stop the graphical IDEA and starting `gralde runIde`.

No error in the gradle console to be seen.

Would you prefer I file this under a new issue?

-Torstein

**Comment by Ruin0x11** [comment]
Yes, let's track a new issue for this. I'll merge the fix.
