### ISSUE TITLE
spacemacs for intellij-lsp-server

### ISSUE THREAD

**Issue by songpeng** [Ruin0x11/intellij-lsp-server#50]
Hi, thanks for your great work to involve this in emacs.
When I use your suggestion for spacemacs, I get the error cannot find lsp-intellij. I guess it might be the wrong names in your suggestion. 
```
(defconst intellij-lsp-packages
  '(
    lsp-mode
    (lsp-intellij :location local)
    ))

(defun intellij-lsp/init-lsp-mode ()
  (use-package lsp-mode))

(defun intellij-lsp/init-lsp-intellij ()
  (with-eval-after-load 'lsp-mode
    (use-package lsp-intellij)
    (add-hook 'java-mode-hook #'lsp-intellij-enable)))
```
You mix the usage of `intellij-lsp` and `lsp-intellij`.

After unifying them as `lsp-intellij`, I get it works, i.e., 
```
(defconst lsp-intellij-packages
  '(
    lsp-mode
    (lsp-intellij :location local)
    lsp-ui
    company-lsp
    ))

(defun lsp-intellij/post-init-lsp-mode ()
  (use-package lsp-mode))

(defun lsp-intellij/init-lsp-intellij ()
  (with-eval-after-load 'lsp-mode
    (use-package lsp-intellij)
    (add-hook 'java-mode-hook #'lsp-intellij-enable)))

(defun lsp-intellij/post-init-lsp-ui ()
  (use-package lsp-ui))
(defun lsp-intellij/post-init-company-lsp ()
  (use-package company-lsp))
```
I use `post-init-lsp-mode` since otherwise emacs tells me two places use `lsp-mode`, and the last one is here. I also add `lsp-ui` and `lsp-company-lsp` here. But I am not familiar with `spacemacs`, so it might be not suitable in a long-run.

**Comment by songpeng** [comment]
When I view java files in the project, I will get the void-function error at your lsp-intellij.el file.
 `(lsp-client-register-uri-handler client "jar" 'lsp-intellij--visit-jar-uri))`
I don't know why, I just comment this, and it then works.

**Comment by Ruin0x11** [comment]
I see. I don't use Spacemacs either so I hadn't come across this. I'll get it to a point that works inside Spacemacs and update the README accordingly.

As for the other comment, do you have the latest version of `lsp-mode`? There was a similar issue a few days ago (#42) where the solution was to install the latest version. To avoid confusion I'll note in the readme that the latest version is required.

Thanks for bringing this up.

**Comment by songpeng** [comment]
Thanks for your response.
Do we have a function to dissemble lsp-intellij, so that I can edit my project in the Intellij IDE without needing to close emacs? Do I miss use lsp-intellij ?

**Comment by songpeng** [comment]
BTW, I  think how to install lsp-intellij in the Readme is not so clear. I mean the first command I see is to use `gradle runIde`.  Although it might be trivial, but `./gradlew clean buildPlugin` and use the zip file under the path build/distributions to locally install in the IntelliJ like intellivim does should be better.

**Comment by Ruin0x11** [comment]
Ok, I'll make sure to add those instructions too.

**Comment by Ruin0x11** [comment]
You can toggle the editor frame with `lsp-intellij-toggle-frame-visibility`. Hoever, keep in mind that there currently isn't support for editing inside IDEA when an LSP session is running. I could investigate whether or not this is feasible if more people want it, however.

**Comment by Ruin0x11** [comment]
I updated the README and moved the Spacemacs layer to [here](https://github.com/Ruin0x11/lsp-intellij-spacemacs). If there are any issues let me know.
