### ISSUE TITLE
De-activated project?

### ISSUE THREAD

**Issue by pajatopmr** [Ruin0x11/intellij-lsp-server#78]
It looks like this project is not getting much love lately (almost nothing in the previous nine months). Can someone comment on the whether further work on this very nice start should take place in a fork or should an effort be made to re-activate this project.
Thanks.

**Comment by Ruin0x11** [comment]
I ended up moving away from Java in my daily work, so I also had less motivation to keep working on this project. Feel free to create a fork to continue work if you wish.

**Comment by pajatopmr** [comment]
Will do. Thanks for replying.
